[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "aws.secretmanager"
version = "0.3.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AWS", "Secret Manager", "Cloud/Subscriptions"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.secretmanager"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.secretmanager-native"
version = "0.3.0"
path = "../native/build/libs/aws.secretmanager-native-0.3.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "time-native"
version = "2.6.0"
path = "./lib/time-native-2.6.0.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "secretsmanager"
version = "2.30.22"
path = "./lib/secretsmanager-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "apache-client"
version = "2.30.22"
path = "./lib/apache-client-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "auth"
version = "2.30.22"
path = "./lib/auth-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-core"
version = "2.30.22"
path = "./lib/aws-core-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-json-protocol"
version = "2.30.22"
path = "./lib/aws-json-protocol-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "checksums"
version = "2.30.22"
path = "./lib/checksums-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "checksums-spi"
version = "2.30.22"
path = "./lib/checksums-spi-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "endpoints-spi"
version = "2.30.22"
path = "./lib/endpoints-spi-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth"
version = "2.30.22"
path = "./lib/http-auth-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-aws"
version = "2.30.22"
path = "./lib/http-auth-aws-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-spi"
version = "2.30.22"
path = "./lib/http-auth-spi-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-client-spi"
version = "2.30.22"
path = "./lib/http-client-spi-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "identity-spi"
version = "2.30.22"
path = "./lib/identity-spi-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "json-utils"
version = "2.30.22"
path = "./lib/json-utils-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "metrics-spi"
version = "2.30.22"
path = "./lib/metrics-spi-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "profiles"
version = "2.30.22"
path = "./lib/profiles-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "protocol-core"
version = "2.30.22"
path = "./lib/protocol-core-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "regions"
version = "2.30.22"
path = "./lib/regions-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "retries"
version = "2.30.22"
path = "./lib/retries-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "retries-spi"
version = "2.30.22"
path = "./lib/retries-spi-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "sdk-core"
version = "2.30.22"
path = "./lib/sdk-core-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "third-party-jackson-core"
version = "2.30.22"
path = "./lib/third-party-jackson-core-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "utils"
version = "2.30.22"
path = "./lib/utils-2.30.22.jar"

[[platform.java21.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpcore"
version = "4.4.16"
path = "./lib/httpcore-4.4.16.jar"

[[platform.java21.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpclient"
version = "4.5.14"
path = "./lib/httpclient-4.5.14.jar"

[[platform.java21.dependency]]
groupId = "org.reactivestreams"
artifactId = "reactive-streams"
version = "1.0.4"
path = "./lib/reactive-streams-1.0.4.jar"
